# Generated by Django 3.0.3 on 2020-03-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200325_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_commented']},
        ),
    ]
